apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "payment.fullname" . }}-common
data:
  backend_host: {{ default "" .Values.config.backend.backend_host | quote }}
  frontend_host: {{ default "" .Values.config.backend.frontend_host | quote }}
  originals_host: {{ default "" .Values.config.backend.originals_host | quote }}
  in_app_host: {{ default "" .Values.config.backend.in_app_host | quote }}
  ethereum_network: {{ default "" .Values.config.backend.ethereum_network | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "payment.fullname" . }}-aws-queue
data:
  rapidCrawlingCollectionQueueName: {{ default "" .Values.config.aws.queue.rapidCrawlingCollectionQueueName | quote }}
  rapidCrawlingCollectionQueueUrl: {{ default "" .Values.config.aws.queue.rapidCrawlingCollectionQueueUrl | quote }}
  rapidCrawlingItemQueueName: {{ default "" .Values.config.aws.queue.rapidCrawlingItemQueueName | quote }}
  rapidCrawlingItemQueueUrl: {{ default "" .Values.config.aws.queue.rapidCrawlingItemQueueUrl | quote }}
  rapidCrawlingRefreshItemMetaQueueName: {{ default "" .Values.config.aws.queue.rapidCrawlingRefreshItemMetaQueueName | quote }}
  rapidCrawlingRefreshItemMetaQueueUrl: {{ default "" .Values.config.aws.queue.rapidCrawlingRefreshItemMetaQueueUrl | quote }}